# Generated by Django 3.2.2 on 2021-08-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipantLoggedIn',
        ),
    ]
