# Generated by Django 3.2.2 on 2021-08-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
